on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GutHub actions
        uses: actions/checkout@v1
        
      - name: Run a one-line script
        run: echo Hello, world!
    
